name: Swift

on:
  push:
    branches: [ feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  Build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Xcode Build
      run: xcodebuild clean -project sharkle.xcodeproj -scheme sharkle -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=15.2'

  SwiftLint:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - name: SwiftLint
         uses: norio-nomura/action-swiftlint@3.2.1
         env:
           WORKING_DIRECTORY: sharkle
